image:
  - Ubuntu2004

environment:
  matrix:
    - LAB: lab0
    - LAB: lab1-0
    - LAB: lab1-1
    - LAB: lab2
    - LAB: lab3-0
    - LAB: lab3-1
    - LAB: lab4
    - LAB: lab5
    - LAB: lab6
    - LAB: lab7
    - LAB: lab8-0
    - LAB: lab8-1
    - LAB: lab9
    - LAB: lab10

test_script:
  - export NORMAL='\033[0m'
  - export YELLOW='\033[1;33m'

  - mkdir -p build_$LAB
  - cd build_$LAB
  - export CTEST_OUTPUT_ON_FAILURE=1
  - STATUS=0

  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DUNLIMITED=ON ../$LAB
  - ninja
  - ninja test || STATUS=1 
  - echo -e "${YELLOW} in.txt ${NORMAL}" && head -c 256 in.txt && echo -e "\n${YELLOW} out.txt ${NORMAL}" && head -c 256 out.txt && echo -e "\n"
  - rm -rf *

  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DUNLIMITED=OFF ../$LAB
  - ninja
  - ninja test || STATUS=1
  - echo -e "${YELLOW} in.txt ${NORMAL}" && head -c 256 in.txt && echo -e "\n${YELLOW} out.txt ${NORMAL}" && head -c 256 out.txt && echo -e "\n"
  - rm -rf *

  - cmake ../$LAB -GNinja -DCMAKE_C_COMPILER=clang -DENABLE_ASAN=true -DUNLIMITED=ON
  - ninja
  - ninja test || STATUS=1
  - echo -e "${YELLOW} in.txt ${NORMAL}" && head -c 256 in.txt && echo -e "\n${YELLOW} out.txt ${NORMAL}" && head -c 256 out.txt && echo -e "\n"
  - rm -rf *

  - cmake ../$LAB -GNinja -DCMAKE_C_COMPILER=clang -DENABLE_USAN=true -DUNLIMITED=ON
  - ninja
  - ninja test || STATUS=1
  - echo -e "${YELLOW} in.txt ${NORMAL}" && head -c 256 in.txt && echo -e "\n${YELLOW} out.txt ${NORMAL}" && head -c 256 out.txt && echo -e "\n"
  - rm -rf *

  - cd ..
  - rm -rf build_$LAB

  - exit $STATUS
