image:
  - Ubuntu2004

environment:
  matrix:
    - LAB: lab0
    - LAB: lab1-0
    - LAB: lab1-1
    - LAB: lab2
    - LAB: lab3-0
    - LAB: lab3-1
    - LAB: lab4
    - LAB: lab5
    - LAB: lab6
    - LAB: lab7
    - LAB: lab8-0
    - LAB: lab8-1
    - LAB: lab9
    - LAB: lab10

test_script:
  - sh: sh test.sh $LAB
