image:
  - Ubuntu2004

matrix:
  fast_finish: false

environment:
  matrix:
    - LAB: lab0
    - LAB: lab1-0
    - LAB: lab1-1
    - LAB: lab2
    - LAB: lab3-0
    - LAB: lab3-1
    - LAB: lab4
    - LAB: lab5
    - LAB: lab6
    - LAB: lab7
    - LAB: lab8-0
    - LAB: lab8-1
    - LAB: lab9
    - LAB: lab10

before_test:
  - sh: mkdir -p build_$LAB
  - sh: cd build_$LAB
  - sh: export CTEST_OUTPUT_ON_FAILURE=1

test_script:
  - sh: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DUNLIMITED=ON ../$LAB
  - sh: ninja
  - sh: ninja test
  - sh: head -c 256 in.txt
  - sh: head -c 256 out.txt
  - sh: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DUNLIMITED=OFF ../$LAB
  - sh: ninja test
  - sh: head -c 256 in.txt
  - sh: head -c 256 out.txt
  - sh: rm -rf *
  - sh: cmake ../$LAB -GNinja -DCMAKE_C_COMPILER=clang -DENABLE_ASAN=true -DUNLIMITED=ON
  - sh: ninja
  - sh: ninja test
  - sh: head -c 256 in.txt
  - sh: head -c 256 out.txt
  - sh: cmake ../$LAB -GNinja -DCMAKE_C_COMPILER=clang -DENABLE_USAN=true -DUNLIMITED=ON
  - sh: ninja
  - sh: ninja test
  - sh: head -c 256 in.txt
  - sh: head -c 256 out.txt