version: 1.0.{build}
image:
- Ubuntu2004
- Visual Studio 2019

before_test:
- ps: >-
    function PrintInOut 
    {
      if ((Test-Path -Path "in.txt") -and (Test-Path -Path "out.txt"))
      {
        Write-Host -ForegroundColor Yellow "in.txt"
        -join [char[]](Get-Content -Path "in.txt" -AsByteStream -totalcount 256)
        Write-Host -ForegroundColor Yellow "out.txt"
        -join [char[]](Get-Content -Path "out.txt" -AsByteStream -totalcount 256)
        Write-Host ""
      }
    }
- ps: $BUILD_DIR = "build_$LAB"
- ps: $STATUS = 0
- ps: >-
    if (Test-Path -Path $BUILD_DIR) 
    { 
      Remove-Item $BUILD_DIR -Force -Recurse 2>&1 > $null 
    }
- ps: New-Item -Path $BUILD_DIR -ItemType "directory" 2>&1 > $null
- ps: Set-Location -Path $BUILD_DIR
- ps: Copy-Item -Path "../.static/img.shields.io/badge/$LAB-failed-blue.svg" -Destination "status.svg"

test_script:
- ps: New-Item -Path "Test1" -ItemType "directory" 2>&1 > $null
- ps: Set-Location -Path "Test1"
- ps: Write-Host -ForegroundColor Yellow "Launch Test1"
- ps: cmake -DUNLIMITED=ON ../../$LAB
- ps: cmake --build . --config Debug
- ps: ctest -C Debug --rerun-failed --output-on-failure || ($STATUS = 1)
- ps: >-
    if ($STATUS -eq 1) 
    {
      PrintInOut
    }
- ps: Set-Location ../

- ps: New-Item -Path "Test2" -ItemType "directory" 2>&1 > $null
- ps:  Set-Location -Path "Test2"
- ps: Write-Host -ForegroundColor Yellow "Launch Test2"
- ps: cmake -DUNLIMITED=OFF ../../$LAB
- ps: cmake --build . --config Debug
- ps: ctest -C Debug --rerun-failed --output-on-failure || ($STATUS = 2)
- ps: >-
    if ($STATUS -eq 2) 
    { 
      PrintInOut
    }
- ps: Set-Location ../

- ps: New-Item -Path "Test3" -ItemType "directory" 2>&1 > $null
- ps: Set-Location -Path "Test3"
- ps: Write-Host -ForegroundColor Yellow "Launch Test3"
- ps: cmake ../../$LAB -DENABLE_ASAN=true -DUNLIMITED=ON
- ps: cmake --build . --config Debug
- ps: ctest -C Debug --rerun-failed --output-on-failure || ($STATUS = 3)
- ps: >-
    if ($STATUS -eq 3) 
    { 
      PrintInOut 
    }
- ps: Set-Location ../

- ps: New-Item -Path "Test4" -ItemType "directory" 2>&1 > $null
- ps: Set-Location -Path "Test4"
- ps: Write-Host -ForegroundColor Yellow "Launch Test4"
- ps: cmake ../../$LAB -DENABLE_USAN=true -DUNLIMITED=ON
- ps: cmake --build . --config Debug
- ps: ctest -C Debug --rerun-failed --output-on-failure || ($STATUS = 4)
- ps: >-
    if ($STATUS -eq 4) 
    { 
      PrintInOut 
    }
- ps: Set-Location ../../

after_test:
- ps: >-
    if ($STATUS -eq 0) 
    { 
      Copy-Item -Path "../.static/img.shields.io/badge/$LAB-passed-green.svg" -Destination "status.svg" 
    }
- ps: exit $STATUS

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true