version: 1.0.{build}
image:
<<<<<<< HEAD
- Ubuntu2004
- Visual Studio 2019
=======
- Visual Studio 2019
- Ubuntu2004
>>>>>>> 83245f5c961f5315a8028a2636d1266ea89edbfb

for:
-
  branches:
    only:
    - master

  environment:
    matrix:
    - LAB: lab0
    - LAB: lab1-0
    - LAB: lab1-1
    - LAB: lab2
    - LAB: lab3-0
    - LAB: lab3-1
    - LAB: lab4
    - LAB: lab5
    - LAB: lab6
    - LAB: lab7
    - LAB: lab8-0
    - LAB: lab8-1
    - LAB: lab9
    - LAB: lab10
    - LAB: lab11
-
  environment:
    matrix:
<<<<<<< HEAD
    - LAB: $env:APPVEYOR_REPO_BRANCH

test_script:
- ps: ./test.ps1 $env:LAB
=======
    - LAB: $(APPVEYOR_REPO_BRANCH)

build: off

test_script:
- pwsh: ./test.ps1 $env:LAB
>>>>>>> 83245f5c961f5315a8028a2636d1266ea89edbfb

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true