version: 1.0.{build}
image:
- Visual Studio 2019
- Ubuntu2004


test_script:
#- ps: >-
#    $HOME_DIR = (pwd).Path
#    foreach ($LAB in (((Get-ChildItem "lab*").FullName).replace("$HOME_DIR\", ""))) 
#    {
#      Write-Host -ForegroundColor Yellow "Testing $LAB..."
#      ./test.ps1 $LAB
#      Write-Host ""
#    }
- ps: echo $(APPVEYOR_REPO_BRANCH)

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true