version: 1.0.{build}
image:
- Ubuntu2004
- Visual Studio 2019

for:
-
  branches:
    only:
    - master
  test_script:
  - pwsh: ./test.ps1
  after_test:
  - pwsh: if (-not (Test-Path -Path "./build_all_labs")) {exit 1}
  - pwsh: 7z a build_test.zip build_all_labs
  - pwsh: Push-AppveyorArtifact build_test.zip
  - pwsh: if (Test-Path -Path "./build_all_labs/Test*/Testing/Temporary/LastTestsFailed.log") {exit 1}
-
  test_script:
  - pwsh: ./test.ps1 -Lab $env:APPVEYOR_REPO_BRANCH
  after_test:
  - pwsh: if (-not (Test-Path -Path "./build_$env:APPVEYOR_REPO_BRANCH")) {exit 1}
  - pwsh: 7z a build_test.zip "build_$env:APPVEYOR_REPO_BRANCH"
  - pwsh: Push-AppveyorArtifact build_test.zip
  - pwsh: if (Test-Path -Path "./build_$env:APPVEYOR_REPO_BRANCH/Test*/Testing/Temporary/LastTestsFailed.log") {exit 1}

build: off
artifacts:
- path: build_test.zip
  name: build_test
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true