version: 1.0.{build}
image:
- Ubuntu2004

test_script:
  - ps: echo $env:APPVEYOR_REPO_BRANCH

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true