version: 1.0.{build}
image:
- Visual Studio 2019
- Ubuntu2004

for:
-
  branches:
    only:
    - master
  test_script:
  - pwsh: ./test.ps1 || exit 1
-  
  test_script:
  - pwsh: ./test.ps1 $enc:APPVEYOR_REPO_BRANCH || exit 1

build: off

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true