version: 1.0.{build}
image:
- Ubuntu2004

environment:
  matrix:
  - job_name: test

  - job_name: lab_test
    job_depends_on: test

  - job_name: master_test
    job_depends_on: test

  - job_name: lab0
    job_depends_on: master_test

  - job_name: lab1-0
    job_depends_on: master_test

  - job_name: lab1-1
    job_depends_on: master_test

  - job_name: lab2
    job_depends_on: master_test

  - job_name: lab3-0
    job_depends_on: master_test

  - job_name: lab3-1
    job_depends_on: master_test

  - job_name: lab4
    job_depends_on: master_test

  - job_name: lab5
    job_depends_on: master_test

  - job_name: lab6
    job_depends_on: master_test

  - job_name: lab7
    job_depends_on: master_test

  - job_name: lab8-0
    job_depends_on: master_test

  - job_name: lab8-1
    job_depends_on: master_test

  - job_name: lab9
    job_depends_on: master_test

  - job_name: lab10
    job_depends_on: master_test

  - job_name: lab11
    job_depends_on: master_test

for:
  -
    matrix:
      only:
        - job_name: test
    test_script:
    - ps: echo test

  -
    matrix:
      only:
        - job_name: lab_test
    test_script:
    - ps: echo lab_test

  -
    matrix:
      only:
        - job_name: lab0
    test_script:
    - ps: echo lab0

  -
    matrix:
      only:
        - job_name: lab1-0
    test_script:
    - ps: echo lab1-0

  -
    matrix:
      only:
        - job_name: lab1-1
    test_script:
    - ps: echo lab1-1

  -
    matrix:
      only:
        - job_name: lab2
    test_script:
    - ps: echo lab2

  -
    matrix:
      only:
        - job_name: lab3-0
    test_script:
    - ps: echo lab3-0

  -
    matrix:
      only:
        - job_name: lab3-1
    test_script:
    - ps: echo lab3-1

  -
    matrix:
      only:
        - job_name: lab4
    test_script:
    - ps: echo lab4

  -
    matrix:
      only:
        - job_name: lab5
    test_script:
    - ps: echo lab5

  -
    matrix:
      only:
        - job_name: lab5
    test_script:
    - ps: echo lab5

  -
    matrix:
      only:
        - job_name: lab6
    test_script:
    - ps: echo lab6

  -
    matrix:
      only:
        - job_name: lab7
    test_script:
    - ps: echo lab7

  -
    matrix:
      only:
        - job_name: lab8-0
    test_script:
    - ps: echo lab8-0

  -
    matrix:
      only:
        - job_name: lab8-1
    test_script:
    - ps: echo lab8-1

  -
    matrix:
      only:
        - job_name: lab9
    test_script:
    - ps: echo lab9

  -
    matrix:
      only:
        - job_name: lab10
    test_script:
    - ps: echo lab10

  -
    matrix:
      only:
        - job_name: lab11
    test_script:
    - ps: echo lab11


notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true