version: 1.0.{build}
image:
- Ubuntu2004

environment:
  matrix:
  - job_name: test

  #- job_name: lab_test
  #  job_depends_on: test
  #  LAB: lab0
  #  branches:
  #    except:
  #    - master

  - job_name: master_test
    job_depends_on: test
    allow_failure: true
    branches:
      only:
      - master

  - job_name: lab0
    job_depends_on: master_test
    LAB: lab0

  - job_name: lab1-0
    job_depends_on: master_test
    LAB: lab1-0

  - job_name: lab1-1
    job_depends_on: master_test
    LAB: lab1-1

  - job_name: lab2
    job_depends_on: master_test
    LAB: lab2

  - job_name: lab3-0
    job_depends_on: master_test
    variable:
      LAB: lab3-0

  - job_name: lab3-1
    job_depends_on: master_test
    LAB: lab3-1

  - job_name: lab4
    job_depends_on: master_test
    LAB: lab4

  - job_name: lab5
    job_depends_on: master_test
    LAB: lab5

  - job_name: lab6
    job_depends_on: master_test
    LAB: lab6

  - job_name: lab7
    job_depends_on: master_test
    LAB: lab7

  - job_name: lab8-0
    job_depends_on: master_test
    LAB: lab8-0

  - job_name: lab8-1
    job_depends_on: master_test
    LAB: lab8-1

  - job_name: lab9
    job_depends_on: master_test
    LAB: lab9

  - job_name: lab10
    job_depends_on: master_test
    LAB: lab10

  - job_name: lab11
    job_depends_on: master_test
    LAB: lab11

for:
  -
    matrix:
      only:
        - job_name: test

    test_script:
    - ps: ./test.ps1 $LAB

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true