name: CMake

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Test
      shell: pwsh
      run: |
        ./test.ps1 
        if (-not (Test-Path -Path "./build_all_labs")) {exit 1}
        if (Test-Path -Path "./build_all_labs/Test*/Testing/Temporary/LastTestsFailed.log") {exit 1}